version: "3"

services:
  eureka-server:
    build: ./eureka-server
    ports:
      - 8761:8761

  zuul-proxy:
    build: ./zuul-proxy
    ports:
      - 8762:8762
    depends_on:
      - eureka-server
    environment:
      SPRING_APPLICATION_NAME: ${ZUUL_APPLICATION_NAME}
      SERVER_PORT: ${ZUUL_PORT}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL}
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

  project-service:
    build: ./project-service
    ports:
      - 8080:8080
    depends_on:
      - eureka-server
    environment:
      SPRING_APPLICATION_NAME: ${PROJECT_APPLICATION_NAME}
      SERVER_PORT: ${PROJECT_PORT}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL}
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_KEY: ${DATABASE_KEY}
      DATABASE_NAME: ${PROJECT_DATABASE_NAME}

  login-service:
    build: ./login-service
    ports:
      - 8070:8070
    depends_on:
      - eureka-server
    environment:
      SPRING_APPLICATION_NAME: ${LOGIN_APPLICATION_NAME}
      SERVER_PORT: ${LOGIN_PORT}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL}
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_KEY: ${DATABASE_KEY}
      DATABASE_NAME: ${LOGIN_DATABASE_NAME}

  news-service:
    build: ./newsfeed-service
    ports:
      - 8090:8090
    depends_on:
      - eureka-server
    environment:
      SPRING_APPLICATION_NAME: ${NEWS_APPLICATION_NAME}
      SERVER_PORT: ${NEWS_PORT}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL}
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_KEY: ${DATABASE_KEY}
      DATABASE_NAME: ${NEWS_DATABASE_NAME}

  react-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
